name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v3

      - name: CMake Setup
        uses: lukka/get-cmake@latest

      - name: VCPKG Setup
        run: |
          git clone git://github.com/Microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg

      - name: eLibrary Setup
        run: |
          cd ..
          git clone git://github.com/eSoftwareOrganization/eLibrary.git

      - name: CMake Build
        run: |
          cd eLibrary
          cmake -DCMAKE_TOOLCHAIN_FILE=./../vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Codecov Uploading
        uses: codecov/codecov-action@v3
