name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v3

      - name: Nasm Setup
        uses: ilammy/setup-nasm@v1

      - name: VCPKG Setup
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b73601a4616c21923cfb6f3a5263a9788165efbd

      - name: CMake Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_FLAGS=--coverage .

      - name: Codecov Uploading
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
