name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v3

      - name: Nasm Setup
        uses: ilammy/setup-nasm@v1

      - name: VCPKG Setup
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 436a061a544c124200200517b9ee55c5bb1b7a26

      - name: LCOV Setup
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: CMake Build
        run: |
          cmake -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build
          cmake --build build

      - name: LCOV Run
        run: |
          lcov -c -d ./ -o coverage.info

      - name: Codecov Uploading
        uses: codecov/codecov-action@v3
        env:
          file: coverage.info
          token: ${{secrets.CODECOV_TOKEN}}
