name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux-Debug",
            os: ubuntu-latest,
            build_type: "Debug"
        }
        - {
            name: "Linux Release",
            os: ubuntu-latest,
            build_type: "Release"
        }
        - {
            name: "MacOS-Debug",
            os: macos-latest,
            build_type: "Debug"
        }
        - {
            name: "MacOS-Release",
            os: macos-latest,
            build_type: "Release"
        }
        - {
            name: "Windows-Debug",
            os: windows-latest,
            build_type: "Debug"
        }
        - {
            name: "Windows-Release",
            os: windows-latest,
            build_type: "Release"
        }
    steps:
      - uses: actions/checkout@v4

      - name: Nasm Setup
        uses: ilammy/setup-nasm@v1

      - name: VCPKG Setup
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 768619a21ef7fb6c5d029a7b141bb7fcef579336

      - name: LCOV Setup
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: CMake Setup
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DELIBRARY_UNIT_TEST=ON -S . -B build

      - name: CMake Build
        run: |
          cmake --build build --config ${{ matrix.config.build_type }}

      - name: Codecov Uploading
        uses: codecov/codecov-action@v3
        env:
          file: coverage.info
          token: ${{secrets.CODECOV_TOKEN}}
