#pragma once

#ifndef eLibraryHeaderCoreStringUnicode
#define eLibraryHeaderCoreStringUnicode

#include <Core/Global.hpp>

namespace eLibrary::Core {
    namespace CharacterBlock {
        enum CharacterBlock {
            Unassigned,
            BasicLatin,
            Latin1Supplement,
            LatinExtendedA,
            LatinExtendedB,
            IPAExtensions,
            SpacingModifierLetters,
            CombiningDiacriticalMarks,
            GreekAndCoptic,
            Cyrillic,
            CyrillicSupplement,
            Armenian,
            Hebrew,
            Arabic,
            Syriac,
            ArabicSupplement,
            Thaana,
            NKo,
            Samaritan,
            Mandaic,
            SyriacSupplement,
            ArabicExtendedB,
            ArabicExtendedA,
            Devanagari,
            Bengali,
            Gurmukhi,
            Gujarati,
            Oriya,
            Tamil,
            Telugu,
            Kannada,
            Malayalam,
            Sinhala,
            Thai,
            Lao,
            Tibetan,
            Myanmar,
            Georgian,
            HangulJamo,
            Ethiopic,
            EthiopicSupplement,
            Cherokee,
            UnifiedCanadianAboriginalSyllabics,
            Ogham,
            Runic,
            Tagalog,
            Hanunoo,
            Buhid,
            Tagbanwa,
            Khmer,
            Mongolian,
            UnifiedCanadianAboriginalSyllabicsExtended,
            Limbu,
            TaiLe,
            NewTaiLue,
            KhmerSymbols,
            Buginese,
            TaiTham,
            CombiningDiacriticalMarksExtended,
            Balinese,
            Sundanese,
            Batak,
            Lepcha,
            OlChiki,
            CyrillicExtendedC,
            GeorgianExtended,
            SundaneseSupplement,
            VedicExtensions,
            PhoneticExtensions,
            PhoneticExtensionsSupplement,
            CombiningDiacriticalMarksSupplement,
            LatinExtendedAdditional,
            GreekExtended,
            GeneralPunctuation,
            SuperscriptsAndSubscripts,
            CurrencySymbols,
            CombiningDiacriticalMarksForSymbols,
            LetterlikeSymbols,
            NumberForms,
            Arrows,
            MathematicalOperators,
            MiscellaneousTechnical,
            ControlPictures,
            OpticalCharacterRecognition,
            EnclosedAlphanumerics,
            BoxDrawing,
            BlockElements,
            GeometricShapes,
            MiscellaneousSymbols,
            Dingbats,
            MiscellaneousMathematicalSymbolsA,
            SupplementalArrowsA,
            BraillePatterns,
            SupplementalArrowsB,
            MiscellaneousMathematicalSymbolsB,
            SupplementalMathematicalOperators,
            MiscellaneousSymbolsAndArrows,
            Glagolitic,
            LatinExtendedC,
            Coptic,
            GeorgianSupplement,
            Tifinagh,
            EthiopicExtended,
            CyrillicExtendedA,
            SupplementalPunctuation,
            CJKRadicalsSupplement,
            KangxiRadicals,
            IdeographicDescriptionCharacters,
            CJKSymbolsAndPunctuation,
            Hiragana,
            Katakana,
            Bopomofo,
            HangulCompatibilityJamo,
            Kanbun,
            BopomofoExtended,
            CJKStrokes,
            KatakanaPhoneticExtensions,
            EnclosedCJKLettersAndMonths,
            CJKCompatibility,
            CJKUnifiedIdeographsExtensionA,
            YijingHexagramSymbols,
            CJKUnifiedIdeographs,
            YiSyllables,
            YiRadicals,
            Lisu,
            Vai,
            CyrillicExtendedB,
            Bamum,
            ModifierToneLetters,
            LatinExtendedD,
            SylotiNagri,
            CommonIndicNumberForms,
            PhagsPa,
            Saurashtra,
            DevanagariExtended,
            KayahLi,
            Rejang,
            HangulJamoExtendedA,
            Javanese,
            MyanmarExtendedB,
            Cham,
            MyanmarExtendedA,
            TaiViet,
            MeeteiMayekExtensions,
            EthiopicExtendedA,
            LatinExtendedE,
            CherokeeSupplement,
            MeeteiMayek,
            HangulSyllables,
            HangulJamoExtendedB,
            HighSurrogates,
            HighPrivateUseSurrogates,
            LowSurrogates,
            PrivateUseArea,
            CJKCompatibilityIdeographs,
            AlphabeticPresentationForms,
            ArabicPresentationFormsA,
            VariationSelectors,
            VerticalForms,
            CombiningHalfMarks,
            CJKCompatibilityForms,
            SmallFormVariants,
            ArabicPresentationFormsB,
            HalfwidthAndFullwidthForms,
            Specials,
            LinearBSyllabary,
            LinearBIdeograms,
            AegeanNumbers,
            AncientGreekNumbers,
            AncientSymbols,
            PhaistosDisc,
            Lycian,
            Carian,
            CopticEpactNumbers,
            OldItalic,
            Gothic,
            OldPermic,
            Ugaritic,
            OldPersian,
            Deseret,
            Shavian,
            Osmanya,
            Osage,
            Elbasan,
            CaucasianAlbanian,
            Vithkuqi,
            LinearA,
            LatinExtendedF,
            CypriotSyllabary,
            ImperialAramaic,
            Palmyrene,
            Nabataean,
            Hatran,
            Phoenician,
            Lydian,
            MeroiticHieroglyphs,
            MeroiticCursive,
            Kharoshthi,
            OldSouthArabian,
            OldNorthArabian,
            Manichaean,
            Avestan,
            InscriptionalParthian,
            InscriptionalPahlavi,
            PsalterPahlavi,
            OldTurkic,
            OldHungarian,
            HanifiRohingya,
            RumiNumeralSymbols,
            Yezidi,
            ArabicExtendedC,
            OldSogdian,
            Sogdian,
            OldUyghur,
            Chorasmian,
            Elymaic,
            Brahmi,
            Kaithi,
            SoraSompeng,
            Chakma,
            Mahajani,
            Sharada,
            SinhalaArchaicNumbers,
            Khojki,
            Multani,
            Khudawadi,
            Grantha,
            Newa,
            Tirhuta,
            Siddham,
            Modi,
            MongolianSupplement,
            Takri,
            Ahom,
            Dogra,
            WarangCiti,
            DivesAkuru,
            Nandinagari,
            ZanabazarSquare,
            Soyombo,
            UnifiedCanadianAboriginalSyllabicsExtendedA,
            PauCinHau,
            DevanagariExtendedA,
            Bhaiksuki,
            Marchen,
            MasaramGondi,
            GunjalaGondi,
            Makasar,
            Kawi,
            LisuSupplement,
            TamilSupplement,
            Cuneiform,
            CuneiformNumbersAndPunctuation,
            EarlyDynasticCuneiform,
            CyproMinoan,
            EgyptianHieroglyphs,
            EgyptianHieroglyphFormatControls,
            AnatolianHieroglyphs,
            BamumSupplement,
            Mro,
            Tangsa,
            BassaVah,
            PahawhHmong,
            Medefaidrin,
            Miao,
            IdeographicSymbolsAndPunctuation,
            Tangut,
            TangutComponents,
            KhitanSmallScript,
            TangutSupplement,
            KanaExtendedB,
            KanaSupplement,
            KanaExtendedA,
            SmallKanaExtension,
            Nushu,
            Duployan,
            ShorthandFormatControls,
            ZnamennyMusicalNotation,
            ByzantineMusicalSymbols,
            MusicalSymbols,
            AncientGreekMusicalNotation,
            KaktovikNumerals,
            MayanNumerals,
            TaiXuanJingSymbols,
            CountingRodNumerals,
            MathematicalAlphanumericSymbols,
            SuttonSignWriting,
            LatinExtendedG,
            GlagoliticSupplement,
            CyrillicExtendedD,
            NyiakengPuachueHmong,
            Toto,
            Wancho,
            NagMundari,
            EthiopicExtendedB,
            MendeKikakui,
            Adlam,
            IndicSiyaqNumbers,
            OttomanSiyaqNumbers,
            ArabicMathematicalAlphabeticSymbols,
            MahjongTiles,
            DominoTiles,
            PlayingCards,
            EnclosedAlphanumericSupplement,
            EnclosedIdeographicSupplement,
            MiscellaneousSymbolsAndPictographs,
            Emoticons,
            OrnamentalDingbats,
            TransportAndMapSymbols,
            AlchemicalSymbols,
            GeometricShapesExtended,
            SupplementalArrowsC,
            SupplementalSymbolsAndPictographs,
            ChessSymbols,
            SymbolsAndPictographsExtendedA,
            SymbolsForLegacyComputing,
            CJKUnifiedIdeographsExtensionB,
            CJKUnifiedIdeographsExtensionC,
            CJKUnifiedIdeographsExtensionD,
            CJKUnifiedIdeographsExtensionE,
            CJKUnifiedIdeographsExtensionF,
            CJKUnifiedIdeographsExtensionI,
            CJKCompatibilityIdeographsSupplement,
            CJKUnifiedIdeographsExtensionG,
            CJKUnifiedIdeographsExtensionH,
            Tags,
            VariationSelectorsSupplement,
            SupplementaryPrivateUseAreaA,
            SupplementaryPrivateUseAreaB,
        };
    }

    namespace CharacterCaseMappingSimple {
        eLibraryAPI const char32_t *doQuery(char32_t) noexcept;

        eLibraryAPI bool isContains(char32_t) noexcept;
    }

    namespace CharacterDerivedCore {
        enum CharacterDerivedProperty : uintmax_t {
            DerivedProperty_Math = 0b00000000000000000000000000000001,
            DerivedProperty_Alphabetic = 0b00000000000000000000000000000010,
            DerivedProperty_Lowercase = 0b00000000000000000000000000000100,
            DerivedProperty_Uppercase = 0b00000000000000000000000000001000,
            DerivedProperty_Cased = 0b00000000000000000000000000010000,
            DerivedProperty_Case_Ignorable =
            0b00000000000000000000000000100000,
            DerivedProperty_Changes_When_Lowercased =
            0b00000000000000000000000001000000,
            DerivedProperty_Changes_When_Uppercased =
            0b00000000000000000000000010000000,
            DerivedProperty_Changes_When_Titlecased =
            0b00000000000000000000000100000000,
            DerivedProperty_Changes_When_Casefolded =
            0b00000000000000000000001000000000,
            DerivedProperty_Changes_When_Casemapped =
            0b00000000000000000000010000000000,
            DerivedProperty_ID_Start = 0b00000000000000000000100000000000,
            DerivedProperty_ID_Continue = 0b00000000000000000001000000000000,
            DerivedProperty_XID_Start = 0b00000000000000000010000000000000,
            DerivedProperty_XID_Continue =
            0b00000000000000000100000000000000,
            DerivedProperty_Default_Ignorable_Code_Point =
            0b00000000000000001000000000000000,
            DerivedProperty_Grapheme_Extend =
            0b00000000000000010000000000000000,
            DerivedProperty_Grapheme_Base =
            0b00000000000000100000000000000000,
            DerivedProperty_Grapheme_Link =
            0b00000000000001000000000000000000,
            DerivedProperty_InCB_Linker =
            0b00000000000010000000000000000000,
            DerivedProperty_InCB_Consonant =
            0b00000000000100000000000000000000,
            DerivedProperty_InCB_Extend =
            0b00000000001000000000000000000000,
        };

        eLibraryAPI uintmax_t doQuery(char32_t) noexcept;
    }

    namespace CharacterEmoji {
        enum CharacterEmoji {
            Unassigned,
            Emoji,
            Emoji_Presentation,
            Emoji_Modifier,
            Emoji_Modifier_Base,
            Emoji_Component,
            Extended_Pictographic,
        };
    }

    namespace CharacterGeneralCategory {
        enum CharacterGeneralCategory {
            Cc, Zs, Po, Sc, Ps,
            Pe, Sm, Pd, Nd, Lu,
            Sk, Pc, Ll, So, Lo,
            Pi, Cf, No, Pf, Lt,
            Lm, Mn, Cn, Me, Mc,
            Nl, Zl, Zp, Cs, Co
        };

        eLibraryAPI CharacterGeneralCategory doQuery(char32_t) noexcept;
    }

    namespace CharacterGraphemeBreak {
        enum class CharacterGraphemeBreak {
            Unassigned,
            Prepend,
            CR,
            LF,
            Control,
            Extend,
            Regional_Indicator,
            SpacingMark,
            L,
            V,
            T,
            LV,
            LVT,
            ZWJ,
        };
    }

    namespace CharacterLineBreak {
        enum CharacterLineBreak {
            BK, CM, CR, GL, LF, NL, SP, WJ, ZW, ZWJ,
            AI, AL, B2, BA, BB, CB, CJ, CL, CP, EB,
            EM, EX, H2, H3, HL, HY, ID, IN, IS, JL,
            JT, JV, NS, NU, OP, PO, PR, QU, RI, SA,
            SG, SY, XX
        };
    }

    namespace CharacterScript {
        enum CharacterScript {
            Unassigned,
            Common,
            Latin,
            Greek,
            Cyrillic,
            Armenian,
            Hebrew,
            Arabic,
            Syriac,
            Thaana,
            Devanagari,
            Bengali,
            Gurmukhi,
            Gujarati,
            Oriya,
            Tamil,
            Telugu,
            Kannada,
            Malayalam,
            Sinhala,
            Thai,
            Lao,
            Tibetan,
            Myanmar,
            Georgian,
            Hangul,
            Ethiopic,
            Cherokee,
            Canadian_Aboriginal,
            Ogham,
            Runic,
            Khmer,
            Mongolian,
            Hiragana,
            Katakana,
            Bopomofo,
            Han,
            Yi,
            Old_Italic,
            Gothic,
            Deseret,
            Inherited,
            Tagalog,
            Hanunoo,
            Buhid,
            Tagbanwa,
            Limbu,
            Tai_Le,
            Linear_B,
            Ugaritic,
            Shavian,
            Osmanya,
            Cypriot,
            Braille,
            Buginese,
            Coptic,
            New_Tai_Lue,
            Glagolitic,
            Tifinagh,
            Syloti_Nagri,
            Old_Persian,
            Kharoshthi,
            Balinese,
            Cuneiform,
            Phoenician,
            Phags_Pa,
            Nko,
            Sundanese,
            Lepcha,
            Ol_Chiki,
            Vai,
            Saurashtra,
            Kayah_Li,
            Rejang,
            Lycian,
            Carian,
            Lydian,
            Cham,
            Tai_Tham,
            Tai_Viet,
            Avestan,
            Egyptian_Hieroglyphs,
            Samaritan,
            Lisu,
            Bamum,
            Javanese,
            Meetei_Mayek,
            Imperial_Aramaic,
            Old_South_Arabian,
            Inscriptional_Parthian,
            Inscriptional_Pahlavi,
            Old_Turkic,
            Kaithi,
            Batak,
            Brahmi,
            Mandaic,
            Chakma,
            Meroitic_Cursive,
            Meroitic_Hieroglyphs,
            Miao,
            Sharada,
            Sora_Sompeng,
            Takri,
            Caucasian_Albanian,
            Bassa_Vah,
            Duployan,
            Elbasan,
            Grantha,
            Pahawh_Hmong,
            Khojki,
            Linear_A,
            Mahajani,
            Manichaean,
            Mende_Kikakui,
            Modi,
            Mro,
            Old_North_Arabian,
            Nabataean,
            Palmyrene,
            Pau_Cin_Hau,
            Old_Permic,
            Psalter_Pahlavi,
            Siddham,
            Khudawadi,
            Tirhuta,
            Warang_Citi,
            Ahom,
            Anatolian_Hieroglyphs,
            Hatran,
            Multani,
            Old_Hungarian,
            SignWriting,
            Adlam,
            Bhaiksuki,
            Marchen,
            Newa,
            Osage,
            Tangut,
            Masaram_Gondi,
            Nushu,
            Soyombo,
            Zanabazar_Square,
            Dogra,
            Gunjala_Gondi,
            Makasar,
            Medefaidrin,
            Hanifi_Rohingya,
            Sogdian,
            Old_Sogdian,
            Elymaic,
            Nandinagari,
            Nyiakeng_Puachue_Hmong,
            Wancho,
            Chorasmian,
            Dives_Akuru,
            Khitan_Small_Script,
            Yezidi,
            Cypro_Minoan,
            Old_Uyghur,
            Tangsa,
            Toto,
            Vithkuqi,
            Kawi,
            Nag_Mundari,
        };
    }

    namespace CharacterSentenceBreak {
        enum CharacterSentenceBreak {
            Unassigned,
            CR,
            LF,
            Extend,
            Sep,
            Format,
            Sp,
            Lower,
            Upper,
            OLetter,
            Numeric,
            ATerm,
            STerm,
            Close,
            SContinue,
        };
    }

    namespace CharacterWordBreak {
        enum CharacterWordBreak {
            Unassigned,
            Double_Quote,
            Single_Quote,
            Hebrew_Letter,
            CR,
            LF,
            Newline,
            Extend,
            Regional_Indicator,
            Format,
            Katakana,
            ALetter,
            MidLetter,
            MidNum,
            MidNumLet,
            Numeric,
            ExtendNumLet,
            ZWJ,
            WSegSpace,
        };
    }
}

#endif
